#!/usr/bin/env npx tsx
/**
 * Generate the sliceable payloads an agent in another repo fetches on demand.
 *
 * The problem this solves is token cost. `llms-full.txt` is the whole corpus at
 * ~166k tokens — more than most agents can spend, and the only slice available
 * before this was `curl | awk` on a category heading. The ladder below lets an
 * agent pay for what it reads:
 *
 *   principles/index.md        pick ids            (all 404, compact)
 *   principles/must.md         the MUST gate       (191 rules)
 *   categories/<id>.md         one category        (rules + prose, no code)
 *   principles/<id>.md         one rule + BOTH examples' source
 *
 * The per-rule payload is the point: 809 example components, 3.3 MB, were
 * unreachable from any endpoint, so an agent got the assertion without the
 * demonstration. Category files deliberately omit example source — 89 rules of
 * code would defeat the reason to fetch a category instead of everything.
 *
 * Output is gitignored and regenerated by `prebuild`; Vite copies public/ into
 * dist/, so the files exist on the deploy without 800+ generated blobs in git.
 */

import { mkdirSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import {
  PUBLIC_DIR,
  SITE,
  loadExampleSources,
  published,
  sourceInfo,
} from './lib/corpus';
import { agentRules } from '../src/data/agentRules';
import { categories } from '../src/data/principles';
import type { Principle } from '../src/types/principle';

const PRINCIPLES_DIR = join(PUBLIC_DIR, 'principles');
const CATEGORIES_DIR = join(PUBLIC_DIR, 'categories');

const examples = loadExampleSources();

/** ~4 chars/token is close enough to size a payload and cheaper than a tokenizer. */
const tokens = (s: string) => Math.round(s.length / 4);

const permalink = (id: string) => `${SITE}/principles/${id}.md`;

const sourceLine = (p: Principle) => {
  const info = sourceInfo(p.source);
  if (!info) return null;
  return `**Source:** ${info.url ? `[${info.name}](${info.url})` : info.name}`;
};

/**
 * Rule + prose, no example code. Shared by the category files and by the head of
 * each per-rule payload — hence `self`, which decides where the cross-link points:
 * a category file sends the reader to the payload, and the payload, which would
 * otherwise cite itself, sends them to the page a human reads.
 */
function ruleSection(p: Principle, heading = '##', self = false): string {
  const rule = agentRules[p.id];
  const out = [`${heading} ${p.title}`, ''];

  const meta = [`**ID:** \`${p.id}\``, `**Category:** ${p.category}`];
  if (rule) meta.unshift(`**${rule.priority}**`);
  out.push(meta.join(' · '));

  const src = sourceLine(p);
  if (src) out.push(src);
  out.push(
    self
      ? `**Interactive version:** ${SITE}/#${p.id}`
      : `**Full rule + examples:** ${permalink(p.id)}`,
    '',
  );

  if (rule) out.push(`> ${rule.priority}: ${rule.rule}`, '');
  out.push(p.description);
  if (p.additionalExplanation) out.push('', p.additionalExplanation);

  return out.join('\n');
}

/** One rule, with both example components inline — the payload agents apply from. */
function rulePayload(p: Principle): string {
  const rule = agentRules[p.id];
  const out = [ruleSection(p, '#', true)];

  if (rule?.codeExample) {
    out.push('', '## Rule snippet', '', '```tsx', rule.codeExample.trim(), '```');
  }

  for (const [label, key] of [
    ['Bad — do not do this', p.badExampleKey],
    ['Good — do this', p.goodExampleKey],
  ] as const) {
    const source = examples.get(key);
    if (!source) continue;
    out.push('', `## ${label}`, '', `\`${key}\``, '', '```tsx', source.trim(), '```');
  }

  if (p.sourceLinks?.length) {
    out.push('', '## References', '');
    out.push(...p.sourceLinks.map((l) => `- [${l.text}](${l.url})`));
  }

  return out.join('\n') + '\n';
}

function ruleJson(p: Principle) {
  const rule = agentRules[p.id];
  const info = sourceInfo(p.source);
  return {
    id: p.id,
    title: p.title,
    category: p.category,
    tags: p.tags ?? [],
    priority: rule?.priority ?? null,
    rule: rule?.rule ?? null,
    ruleSnippet: rule?.codeExample ?? null,
    description: p.description,
    explanation: p.additionalExplanation ?? null,
    source: info ? { id: p.source, name: info.name, url: info.url ?? null } : null,
    references: p.sourceLinks ?? [],
    examples: {
      bad: { key: p.badExampleKey, source: examples.get(p.badExampleKey) ?? null },
      good: { key: p.goodExampleKey, source: examples.get(p.goodExampleKey) ?? null },
    },
    urls: { markdown: permalink(p.id), json: `${SITE}/principles/${p.id}.json` },
  };
}

/** Compact enough that reading the whole index is an affordable first move. */
function indexMd(): string {
  const out = [
    '# Rule index',
    '',
    `${published.length} rules across ${categories.length} categories. This index is`,
    'ids and titles only — fetch what you need:',
    '',
    `- one rule, with its good and bad example source: \`${SITE}/principles/<id>.md\``,
    `- one category, rules and prose only: \`${SITE}/categories/<category>.md\``,
    `- every MUST rule, as a gate: \`${SITE}/principles/must.md\``,
    '',
  ];

  for (const c of categories) {
    const items = published.filter((p) => p.category === c.id);
    if (!items.length) continue;
    out.push(`## ${c.id} (${items.length})`, '');
    for (const p of items) {
      const priority = agentRules[p.id]?.priority ?? '—';
      const tags = p.tags?.length ? ` [${p.tags.join(', ')}]` : '';
      out.push(`- \`${p.id}\` ${priority} — ${p.title}${tags}`);
    }
    out.push('');
  }

  return out.join('\n');
}

function mustMd(): string {
  const must = published.filter((p) => agentRules[p.id]?.priority === 'MUST');
  const out = [
    '# MUST rules',
    '',
    `${must.length} of ${published.length} rules are MUST. This file is the whole set,`,
    'phrased to be checked against a diff.',
    '',
    `For the good and bad example that disambiguates any one of them, fetch`,
    `\`${SITE}/principles/<id>.md\` — ids are the backticked strings below.`,
    '',
  ];

  for (const c of categories) {
    const items = must.filter((p) => p.category === c.id);
    if (!items.length) continue;
    out.push(`## ${c.id}`, '');
    for (const p of items) {
      out.push(`- \`${p.id}\` — ${agentRules[p.id].rule}`);
    }
    out.push('');
  }

  return out.join('\n');
}

function categoryMd(categoryId: string): string {
  const c = categories.find((x) => x.id === categoryId)!;
  const items = published.filter((p) => p.category === categoryId);
  return [
    `# ${c.title}`,
    '',
    `> ${c.description}. ${items.length} rules.`,
    '',
    'Rules and reasoning only — no example code, to keep this affordable. For the',
    'good and bad component source of any rule, fetch its own payload.',
    '',
    '---',
    '',
    items.map((p) => ruleSection(p)).join('\n\n---\n\n'),
    '',
  ].join('\n');
}

// Wipe and rebuild, so a renamed or deleted principle cannot leave a stale payload
// being served — these directories are generated in full every time.
rmSync(PRINCIPLES_DIR, { recursive: true, force: true });
rmSync(CATEGORIES_DIR, { recursive: true, force: true });
mkdirSync(PRINCIPLES_DIR, { recursive: true });
mkdirSync(CATEGORIES_DIR, { recursive: true });

let missingExamples = 0;
for (const p of published) {
  const md = rulePayload(p);
  writeFileSync(join(PRINCIPLES_DIR, `${p.id}.md`), md, 'utf8');
  writeFileSync(
    join(PRINCIPLES_DIR, `${p.id}.json`),
    JSON.stringify(ruleJson(p), null, 2),
    'utf8',
  );
  if (!examples.has(p.badExampleKey) || !examples.has(p.goodExampleKey)) missingExamples++;
}

const index = indexMd();
const must = mustMd();
writeFileSync(join(PRINCIPLES_DIR, 'index.md'), index, 'utf8');
writeFileSync(join(PRINCIPLES_DIR, 'must.md'), must, 'utf8');

for (const c of categories) {
  if (!published.some((p) => p.category === c.id)) continue;
  writeFileSync(join(CATEGORIES_DIR, `${c.id}.md`), categoryMd(c.id), 'utf8');
}

console.log(`  principles/          ${published.length * 2} files (.md + .json per rule)`);
console.log(`  principles/index.md  ${String(tokens(index)).padStart(6)} tokens`);
console.log(`  principles/must.md   ${String(tokens(must)).padStart(6)} tokens`);
for (const c of categories) {
  if (!published.some((p) => p.category === c.id)) continue;
  console.log(`  categories/${c.id.padEnd(13)}${String(tokens(categoryMd(c.id))).padStart(6)} tokens`);
}

/**
 * The example source is the reason these payloads exist, so its absence is a build
 * failure rather than a quietly thinner file. Same posture as the llms.txt guard.
 */
if (missingExamples > 0) {
  throw new Error(
    `${missingExamples} principle(s) have a bad/goodExampleKey with no matching component — ` +
      'the per-rule payloads would ship without the code they exist to carry.',
  );
}
console.log(`\nAll ${published.length} rules carry both example sources.`);
